language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=25.0.0
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
    - build-tools-24
    # The SDK version used to compile your project
    - android-${ANDROID_API_LEVEL}
    - android-25
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    #- addon-google_apis-google-${ANDROID_API_LEVEL}
    - sys-img-${ANDROID_ABI}-google_apis-${ANDROID_API_LEVEL}
#licenses:
#    - 'android-sdk-preview-.+'
#    - 'android-sdk-license-.+'
#    - 'google-gdk-license-.+'
before_script:
  - echo no | android create avd --force -n test -t ${ANDROID_TARGET} --abi ${ANDROID_ABI} --tag ${ANDROID_TAG}
  - emulator -avd test -no-window &
  - android-wait-for-emulator
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - ./gradlew jacocoTestReport coveralls